import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { useAuthStore } from '../stores/authStore'
import { supabase } from '../services/supabase'

type Language = 'th' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => Promise<void>
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  th: {
    // Navigation
    'nav.dashboard': 'แดชบอร์ด',
    'nav.pos': 'ขายสินค้า (POS)',
    'nav.aiSymptomChecker': 'AI ช่วยแนะนำยา',
    'nav.categories': 'หมวดหมู่',
    'nav.products': 'สินค้า',
    'nav.inventory': 'คลังสินค้า',
    'nav.reports': 'รายงาน',
    'nav.settings': 'ตั้งค่า',
    'nav.logout': 'ออกจากระบบ',
    'nav.salesOrders': 'รายการขาย',
    'nav.stockManagement': 'จัดการสต็อก',
    'nav.contacts': 'ผู้ติดต่อ',
    'nav.documents': 'เอกสาร',
    'nav.platformManagement': 'จัดการแพลตฟอร์ม',
    'nav.crossChannelStock': 'ตัดสต็อก',
    'nav.website': 'เว็บไซต์ร้าน',
    'nav.billScan': 'สแกนบิล OCR',
    'nav.taxInvoices': 'ใบกำกับภาษีฝั่งขาย',
    'nav.workSchedule': 'ตารางเข้างาน',
    // Section titles
    'nav.section.main': 'หลัก',
    'nav.section.products': 'สินค้า',
    'nav.section.contacts': 'ผู้ติดต่อ',
    'nav.section.documents': 'เอกสาร',
    'nav.section.settings': 'ตั้งค่า',
    
    // Login
    'login.title': 'More Drug Store',
    'login.subtitle': 'ระบบขายหน้าร้านสำหรับร้านขายยา',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.rememberMe': 'จดจำข้อมูลการเข้าสู่ระบบ',
    'login.showPassword': 'แสดงรหัสผ่าน',
    'login.hidePassword': 'ซ่อนรหัสผ่าน',
    'login.submit': 'เข้าสู่ระบบ',
    'login.footer': 'ติดต่อผู้ดูแลระบบหากต้องการรีเซ็ตรหัสผ่านใหม่',
    'login.invalidCredentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
    'login.error': 'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    
    // Dashboard
    'dashboard.title': 'แดชบอร์ด',
    'dashboard.welcome': 'ยินดีต้อนรับ',
    'dashboard.todaySales': 'ยอดขายวันนี้',
    'dashboard.salesCount': 'รายการขาย',
    'dashboard.totalProducts': 'สินค้าทั้งหมด',
    'dashboard.lowStock': 'สินค้าใกล้หมด',
    'dashboard.recentSales': 'ยอดขายล่าสุด',
    'dashboard.noSalesData': 'ยังไม่มีข้อมูลการขาย',
    'dashboard.noLowStock': 'ไม่มีสินค้าที่ใกล้หมด',
    
    // POS
    'pos.title': 'ขายสินค้า (POS)',
    'pos.search': 'ค้นหาสินค้า...',
    'pos.cart': 'รายการสินค้า',
    'pos.empty': 'ไม่มีสินค้าในตะกร้า',
    'pos.subtotal': 'ยอดรวม',
    'pos.checkout': 'ชำระเงิน',
    'pos.quantity': 'จำนวน',
    'pos.remove': 'ลบ',
    'pos.scanOrType': 'สแกนหรือพิมพ์บาร์โค้ดสินค้า...',
    'pos.emptyCart': 'ยังไม่มีสินค้าในตะกร้า',
    'pos.emptyCartHint': 'สแกนบาร์โค้ดเพื่อเพิ่มสินค้า',
    'pos.orderSummary': 'สรุปรายการ',
    'pos.defaultCustomer': 'ลูกค้าทั่วไป',
    'pos.sellingVia': 'กำลังขายผ่าน:',
    'pos.paymentMethod': 'วิธีชำระ:',
    'pos.otherMethods': 'อื่นๆ',
    'pos.customerPays': 'ลูกค้าชำระ:',
    'pos.discount': 'ส่วนลด',
    'pos.totalPayable': 'ยอดชำระ',
    'pos.pay': 'ชำระเงิน',
    'pos.hold': 'พัก',
    'pos.print': 'พิมพ์',
    'pos.salesChannel': 'ช่องทางการขาย',
    'pos.browseByCategory': 'ยาตามหมวดหมู่',
    'pos.printLabel': 'พิมพ์ฉลาก',
    'pos.summaryCount': 'สรุปยอด / นับเงิน',
    'pos.paymentSummary': 'สรุปยอดชำระเงิน',
    'pos.countMoney': 'นับเงิน',
    'pos.recentSales': 'รายการขายล่าสุด',
    'pos.heldBills': 'บิลที่พักไว้',
    'pos.viewAll': 'ดูทั้งหมด',
    'pos.latest': 'ล่าสุด',
    'pos.alertHistory': 'ประวัติการแจ้งเตือน',
    'pos.addToCart': 'เพิ่มสินค้าในตะกร้า',
    'pos.change': 'เงินทอน',
    'pos.confirmSale': 'ยืนยันการขาย',
    'pos.saleSuccess': 'ขายสำเร็จ!',
    'pos.orderNumber': 'เลขออเดอร์',
    'pos.holdBillSuccess': 'พักบิลเรียบร้อยแล้ว',
    'pos.deleteHeldBill': 'ต้องการลบบิลที่พักไว้นี้ใช่หรือไม่?',
    'pos.userManual': 'คู่มือการใช้งาน',
    
    // Categories
    'categories.title': 'หมวดหมู่สินค้า',
    'categories.addCategory': 'เพิ่มหมวดหมู่',
    'categories.editCategory': 'แก้ไขหมวดหมู่',
    'categories.deleteCategory': 'ลบหมวดหมู่',
    'categories.nameTh': 'ชื่อภาษาไทย',
    'categories.nameEn': 'ชื่อภาษาอังกฤษ',
    'categories.parentCategory': 'หมวดหมู่หลัก',
    'categories.noParent': 'ไม่มีหมวดหมู่หลัก',
    'categories.sortOrder': 'ลำดับการแสดง',
    'categories.actions': 'จัดการ',
    'categories.edit': 'แก้ไข',
    'categories.delete': 'ลบ',
    'categories.noCategories': 'ไม่พบหมวดหมู่',
    'categories.addCategoryPrompt': 'กรุณาเพิ่มหมวดหมู่สินค้า',
    'categories.loading': 'กำลังโหลดหมวดหมู่...',
    'categories.confirmDelete': 'คุณแน่ใจหรือไม่ที่จะลบหมวดหมู่นี้?',
    'categories.deleteSuccess': 'ลบหมวดหมู่สำเร็จ',
    'categories.saveSuccess': 'บันทึกหมวดหมู่สำเร็จ',
    'categories.modalTitle': 'จัดการหมวดหมู่',
    'categories.hasProducts': 'ไม่สามารถลบหมวดหมู่นี้ได้: มีสินค้า {count} รายการที่ใช้หมวดหมู่นี้อยู่',
    
    // Products
    'products.title': 'สินค้า',
    'products.addProduct': 'เพิ่มสินค้า',
    'products.search': 'ค้นหาสินค้า (ชื่อ, บาร์โค้ด)',
    'products.barcode': 'บาร์โค้ด',
    'products.name': 'ชื่อสินค้า',
    'products.category': 'หมวดหมู่',
    'products.price': 'ราคา',
    'products.stock': 'คงเหลือ',
    'products.actions': 'จัดการ',
    'products.edit': 'แก้ไข',
    'products.noCategory': 'ไม่มีหมวดหมู่',
    'products.noProducts': 'ไม่พบสินค้า',
    'products.addProductPrompt': 'กรุณาเพิ่มสินค้าใหม่',
    'products.loading': 'กำลังโหลดสินค้า...',
    'products.sku': 'รหัสสินค้า',
    'products.nameTh': 'ชื่อภาษาไทย',
    'products.nameEn': 'ชื่อภาษาอังกฤษ',
    'products.descriptionTh': 'รายละเอียดภาษาไทย',
    'products.descriptionEn': 'รายละเอียดภาษาอังกฤษ',
    'products.basePrice': 'ราคาขาย',
    'products.costPrice': 'ราคาทุน',
    'products.stockQuantity': 'จำนวนคงเหลือ',
    'products.minStockLevel': 'จำนวนขั้นต่ำ',
    'products.unit': 'หน่วย',
    'products.image': 'รูปภาพ',
    'products.uploadImage': 'อัปโหลดรูปภาพ',
    'products.editProduct': 'แก้ไขสินค้า',
    'products.saveSuccess': 'บันทึกสินค้าสำเร็จ',
    'products.filterByCategory': 'กรองตามหมวดหมู่',
    'products.filterByPrice': 'กรองตามราคา',
    'products.filterByStock': 'กรองตามสต็อก',
    'products.allCategories': 'ทุกหมวดหมู่',
    'products.lowStock': 'สต็อกต่ำ',
    'products.inStock': 'มีสต็อก',
    'products.outOfStock': 'หมดสต็อก',
    'products.priceRange': 'ช่วงราคา',
    'products.minPrice': 'ราคาต่ำสุด',
    'products.maxPrice': 'ราคาสูงสุด',
    'products.clearFilters': 'ล้างตัวกรอง',
    
    // Inventory
    'inventory.title': 'คลังสินค้า',
    'inventory.comingSoon': 'เร็วๆ นี้',
    
    // Reports
    'reports.title': 'รายงาน',
    'reports.comingSoon': 'เร็วๆ นี้',
    
    // AI Symptom Checker
    'ai.title': 'AI ช่วยแนะนำยา',
    'ai.subtitle': 'ระบบช่วยแนะนำยาตามอาการ',
    'ai.disclaimer': '⚠️ ข้อจำกัดความรับผิดชอบ: ระบบนี้เป็นเพียงข้อมูลเบื้องต้น ไม่ใช่การวินิจฉัยโรค หากอาการรุนแรงหรือไม่ดีขึ้น กรุณาพบแพทย์',
    'ai.patientInfo': 'ข้อมูลผู้ป่วย',
    'ai.age': 'อายุ',
    'ai.ageYears': 'ปี',
    'ai.pregnant': 'ท้องหรือให้นมบุตร?',
    'ai.yes': 'ใช่',
    'ai.no': 'ไม่ใช่',
    'ai.allergies': 'แพ้ยาอะไรบ้าง?',
    'ai.allergiesPlaceholder': 'เช่น แพ้เพนนิซิลลิน, แพ้แอสไพริน',
    'ai.currentMeds': 'กำลังกินยาอะไรอยู่?',
    'ai.currentMedsPlaceholder': 'เช่น ยาลดความดัน, ยาเบาหวาน',
    'ai.chronicConditions': 'มีโรคประจำตัวไหม?',
    'ai.chronicConditionsPlaceholder': 'เช่น เบาหวาน, ความดันโลหิตสูง, หอบหืด',
    'ai.symptomDuration': 'มีอาการมานานแค่ไหน?',
    'ai.lessThan1Day': 'น้อยกว่า 1 วัน',
    'ai.1to3Days': '1-3 วัน',
    'ai.3to7Days': '3-7 วัน',
    'ai.moreThan1Week': 'มากกว่า 1 สัปดาห์',
    'ai.symptoms': 'อาการที่พบ',
    'ai.symptomsPlaceholder': 'อธิบายอาการโดยละเอียด เช่น ปวดหัว มีไข้ เจ็บคอ ไอ น้ำมูก',
    'ai.analyze': 'วิเคราะห์และแนะนำยา',
    'ai.analyzing': 'กำลังวิเคราะห์...',
    'ai.results': 'ผลการวิเคราะห์',
    'ai.recommendations': 'ยาที่แนะนำ',
    'ai.warnings': 'คำเตือน',
    'ai.dosage': 'วิธีใช้',
    'ai.price': 'ราคา',
    'ai.stock': 'คงเหลือ',
    'ai.addToCart': 'เพิ่มลงตะกร้า',
    'ai.noResults': 'ไม่พบยาที่เหมาะสม กรุณาปรึกษาเภสัชกรหรือแพทย์',
    'ai.error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'ai.apiKeyMissing': 'กรุณาตั้งค่า Google Gemini API Key ใน .env',
    'ai.seeDoctor': 'แนะนำให้พบแพทย์',
    'ai.reset': 'เริ่มใหม่',
    
    // User Management
    'userManagement.title': 'การจัดการผู้ใช้',
    'userManagement.subtitle': 'จัดการบัญชีผู้ใช้และสิทธิ์การเข้าถึง',
    'userManagement.addUser': 'เพิ่มผู้ใช้',
    'userManagement.editUser': 'แก้ไขผู้ใช้',
    'userManagement.username': 'ชื่อผู้ใช้ (Username)',
    'userManagement.email': 'อีเมล',
    'userManagement.fullName': 'ชื่อเต็ม',
    'userManagement.role': 'บทบาท',
    'userManagement.password': 'รหัสผ่าน',
    'userManagement.active': 'เปิดใช้งาน',
    'userManagement.search': 'ค้นหาผู้ใช้...',
    'userManagement.noUsers': 'ไม่พบผู้ใช้',
    'userManagement.addUserPrompt': 'คลิก "เพิ่มผู้ใช้" เพื่อสร้างบัญชีใหม่',
    'userManagement.cancel': 'ยกเลิก',
    'userManagement.save': 'บันทึก',
    'userManagement.create': 'สร้าง',
    'userManagement.emailAuto': 'อีเมล (เว้นว่าง = สร้างอัตโนมัติ)',
    'userManagement.passwordHint': 'รหัสผ่าน (เว้นว่าง = 888888)',
    'userManagement.activeAccount': 'เปิดใช้งานบัญชีนี้',
    
    // Roles
    'role.owner': 'เจ้าของร้าน',
    'role.manager': 'ผู้จัดการร้าน',
    'role.pharmacist': 'เภสัชกร',
    'role.partTime': 'พาร์ทไทม์',
    'role.accountant': 'นักบัญชี',
    
    // Settings
    'settings.title': 'ตั้งค่า',
    'settings.subtitle': 'ตั้งค่าระบบและการเชื่อมต่อ',
    'settings.userManagement': 'การจัดการผู้ใช้',
    'settings.helpManual': 'คู่มือการใช้งาน',
    // Settings - Business
    'settings.section.business': 'ตั้งค่าธุรกิจ',
    'settings.section.externalConnections': 'ตั้งค่าการเชื่อมต่อภายนอก',
    'settings.section.audit': 'Audit - ตรวจสอบและควบคุม',
    'settings.dashboard': 'แดชบอร์ด',
    'settings.dashboardDesc': 'ภาพรวมยอดขายและสถิติ',
    'settings.salesChannels': 'ช่องทางการขาย',
    'settings.salesChannelsDesc': 'ตั้งค่าแล้ว',
    'settings.salesChannelsUnit': 'ช่องทาง',
    'settings.paymentChannels': 'ช่องทางการชำระเงิน',
    'settings.paymentChannelsDesc': 'ตั้งค่าวิธีการรับเงิน',
    'settings.paymentChannelsStatus': 'เปิดใช้งาน',
    'settings.shopInfo': 'ข้อมูลร้าน',
    'settings.userManagementTitle': 'การจัดการผู้ใช้',
    'settings.userManagementDesc': 'ผู้ใช้งานในระบบ',
    'settings.usersCount': 'ผู้ใช้งาน',
    'settings.employeeManagement': 'จัดการพนักงาน',
    'settings.employeeManagementDesc': 'ตั้งค่าพนักงานและสิทธิ์การใช้งาน',
    'settings.warehouse': 'คลังสินค้า',
    'settings.warehouseDesc': 'จัดการคลังสินค้าและสต็อก',
    'settings.productCategories': 'หมวดหมู่สินค้า',
    'settings.productCategoriesDesc': 'จัดการหมวดหมู่และหมวดหมู่ย่อย',
    'settings.expenseCategories': 'หมวดหมู่ค่าใช้จ่าย',
    'settings.expenseCategoriesDesc': 'ตั้งค่ารหัสและแผนผังบัญชี',
    'settings.paymentRules': 'กฎการชำระเงิน',
    'settings.paymentRulesDesc': 'ตั้งค่าวิธีการชำระเงินตามคีย์เวิร์ด',
    // Settings - External Connections
    'settings.flowAccount': 'การเชื่อมต่อ FlowAccount',
    'settings.flowAccountDesc': 'บัญชีและใบกำกับภาษี',
    'settings.flowAccountConnected': 'เชื่อมต่อแล้ว',
    'settings.flowAccountDisconnected': 'ยังไม่เชื่อมต่อ',
    'settings.zortOut': 'การเชื่อมต่อ ZortOut',
    'settings.zortOutDesc': 'ระบบจัดการสต็อก',
    'settings.zortOutStatus': 'พร้อมใช้งาน',
    // Settings - Audit
    'settings.executiveSummary': 'สรุปภาพรวมธุรกิจ',
    'settings.executiveSummaryDesc': 'Executive Summary สำหรับผู้บริหาร',
    'settings.cashierClosing': 'รายงานปิดร้าน / นับเงิน',
    'settings.cashierClosingDesc': 'ตรวจสอบประวัติการปิดร้านและยอดเงินในเก๊ะ',
    'settings.negativeStock': 'รายงานสินค้าติดลบ',
    'settings.negativeStockDesc': 'ตรวจสอบสินค้าที่สต็อกติดลบและการเคลื่อนไหว',
    'settings.stockAdjustment': 'รายงานการปรับยอดสต็อก',
    'settings.stockAdjustmentDesc': 'ตรวจสอบการปรับยอดสต็อกโดยผู้ใช้งาน',
    'settings.stockTransfer': 'รายงานการโอนสินค้าระหว่างคลัง',
    'settings.stockTransferDesc': 'ตรวจสอบการเคลื่อนย้ายสินค้าระหว่างคลัง',
    'settings.abnormalOrders': 'รายงานออเดอร์ไม่ปกติ',
    'settings.abnormalOrdersDesc': 'ตรวจสอบการแก้ไขราคาและของแถม',
    'settings.receiptTaxInvoice': 'รายงานใบเสร็จ/ใบกำกับภาษี',
    'settings.receiptTaxInvoiceDesc': 'ตรวจสอบรายการขอใบเสร็จและใบกำกับภาษี',
    'settings.nearExpiry': 'สินค้าใกล้หมดอายุ',
    'settings.nearExpiryDesc': 'ตรวจสอบสินค้าใกล้วันหมดอายุ',
    'settings.helpManagement': 'จัดการคู่มือการใช้งาน',
    'settings.helpManagementDesc': 'สร้างและแก้ไขคู่มือสำหรับแต่ละหน้า',
    
    // Page Titles (for pages linked from sidebar)
    'page.pos.title': 'ขายสินค้า',
    'page.pos.subtitle': 'ระบบขายหน้าร้าน',
    'page.salesOrders.title': 'รายการขาย',
    'page.products.title': 'สินค้า',
    'page.products.subtitle': 'จัดการสินค้าทั้งหมด',
    'page.platformManagement.title': 'จัดการแพลตฟอร์ม',
    'page.platformManagement.subtitle': 'จัดการสินค้าในแต่ละแพลตฟอร์ม',
    'page.crossChannelStock.title': 'ตัดสต็อกข้ามช่องทาง',
    'page.crossChannelStock.subtitle': 'รายงานการตัดสต็อกข้ามช่องทาง',
    'page.contacts.title': 'ผู้ติดต่อ',
    'page.contacts.subtitle': 'จัดการลูกค้าและซัพพลายเออร์',
    'page.expenses.title': 'เอกสาร',
    'page.expenses.subtitle': 'จัดการเอกสารทั้งหมด',
    'page.billScan.title': 'สแกนบิล OCR',
    'page.billScan.subtitle': 'สแกนและบันทึกบิลอัตโนมัติ',
    'page.taxInvoices.title': 'ใบกำกับภาษีฝั่งขาย',
    'page.taxInvoices.subtitle': 'จัดการใบกำกับภาษี',
    'page.workSchedule.title': 'ตารางเข้างาน',
    'page.workSchedule.subtitle': 'จัดการตารางเวลาทำงาน',
    'page.dashboard.subtitle': 'ภาพรวมยอดขายและสถิติ',
    'page.warehouse.title': 'คลังสินค้า',
    'page.warehouse.subtitle': 'จัดการคลังสินค้าและสต็อก',
    'page.categories.title': 'หมวดหมู่สินค้า',
    'page.categories.subtitle': 'จัดการหมวดหมู่และหมวดหมู่ย่อย',
    'page.paymentMethods.title': 'ช่องทางการชำระเงิน',
    'page.paymentMethods.subtitle': 'ตั้งค่าวิธีการรับเงิน',

    // Common
    'common.loading': 'กำลังโหลด...',
    'common.inactive': 'ระงับ',
    'common.save': 'บันทึก',
    'common.cancel': 'ยกเลิก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.confirm': 'ยืนยัน',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.export': 'ส่งออก',
    'common.import': 'นำเข้า',
    'common.add': 'เพิ่ม',
    'common.baht': '฿',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.pos': 'Point of Sale (POS)',
    'nav.aiSymptomChecker': 'AI Symptom Checker',
    'nav.categories': 'Categories',
    'nav.products': 'Products',
    'nav.inventory': 'Inventory',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.salesOrders': 'Sales Orders',
    'nav.stockManagement': 'Stock Management',
    'nav.contacts': 'Contacts',
    'nav.documents': 'Documents',
    'nav.platformManagement': 'Platform Management',
    'nav.crossChannelStock': 'Cross-Channel Stock',
    'nav.website': 'Store Website',
    'nav.billScan': 'Bill Scan OCR',
    'nav.taxInvoices': 'Sales Tax Invoices',
    'nav.workSchedule': 'Work Schedule',
    // Section titles
    'nav.section.main': 'Main',
    'nav.section.products': 'Products',
    'nav.section.contacts': 'Contacts',
    'nav.section.documents': 'Documents',
    'nav.section.settings': 'Settings',
    
    // Login
    'login.title': 'More Drug Store',
    'login.subtitle': 'Pharmacy Point of Sale System',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',
    'login.submit': 'Sign In',
    'login.footer': 'Contact administrator to reset your password',
    'login.invalidCredentials': 'Invalid email or password',
    'login.error': 'Login failed. Please try again',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.todaySales': 'Today\'s Sales',
    'dashboard.salesCount': 'Sales Count',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.recentSales': 'Recent Sales',
    'dashboard.noSalesData': 'No sales data yet',
    'dashboard.noLowStock': 'No low stock items',
    
    // POS
    'pos.title': 'Point of Sale',
    'pos.search': 'Search products...',
    'pos.cart': 'Shopping Cart',
    'pos.empty': 'Cart is empty',
    'pos.subtotal': 'Subtotal',
    'pos.checkout': 'Checkout',
    'pos.quantity': 'Quantity',
    'pos.remove': 'Remove',
    'pos.scanOrType': 'Scan or type barcode...',
    'pos.emptyCart': 'No items in cart',
    'pos.emptyCartHint': 'Scan barcode to add items',
    'pos.orderSummary': 'Order Summary',
    'pos.defaultCustomer': 'Walk-in Customer',
    'pos.sellingVia': 'Selling via:',
    'pos.paymentMethod': 'Payment:',
    'pos.otherMethods': 'Other',
    'pos.customerPays': 'Customer pays:',
    'pos.discount': 'Discount',
    'pos.totalPayable': 'Total',
    'pos.pay': 'Pay',
    'pos.hold': 'Hold',
    'pos.print': 'Print',
    'pos.salesChannel': 'Sales Channel',
    'pos.browseByCategory': 'Browse by Category',
    'pos.printLabel': 'Print Labels',
    'pos.summaryCount': 'Summary / Count',
    'pos.paymentSummary': 'Payment Summary',
    'pos.countMoney': 'Count Money',
    'pos.recentSales': 'Recent Sales',
    'pos.heldBills': 'Held Bills',
    'pos.viewAll': 'View All',
    'pos.latest': 'Latest',
    'pos.alertHistory': 'Alert History',
    'pos.addToCart': 'Add to cart',
    'pos.change': 'Change',
    'pos.confirmSale': 'Confirm Sale',
    'pos.saleSuccess': 'Sale completed!',
    'pos.orderNumber': 'Order No.',
    'pos.holdBillSuccess': 'Bill held successfully',
    'pos.deleteHeldBill': 'Delete this held bill?',
    'pos.userManual': 'User Manual',
    
    // Categories
    'categories.title': 'Product Categories',
    'categories.addCategory': 'Add Category',
    'categories.editCategory': 'Edit Category',
    'categories.deleteCategory': 'Delete Category',
    'categories.nameTh': 'Thai Name',
    'categories.nameEn': 'English Name',
    'categories.parentCategory': 'Parent Category',
    'categories.noParent': 'No Parent',
    'categories.sortOrder': 'Sort Order',
    'categories.actions': 'Actions',
    'categories.edit': 'Edit',
    'categories.delete': 'Delete',
    'categories.noCategories': 'No categories found',
    'categories.addCategoryPrompt': 'Please add product categories',
    'categories.loading': 'Loading categories...',
    'categories.confirmDelete': 'Are you sure you want to delete this category?',
    'categories.deleteSuccess': 'Category deleted successfully',
    'categories.saveSuccess': 'Category saved successfully',
    'categories.modalTitle': 'Manage Category',
    'categories.hasProducts': 'Cannot delete this category: {count} products are using this category',
    
    // Products
    'products.title': 'Products',
    'products.addProduct': 'Add Product',
    'products.search': 'Search products (name, barcode)',
    'products.barcode': 'Barcode',
    'products.name': 'Product Name',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.actions': 'Actions',
    'products.edit': 'Edit',
    'products.noCategory': 'No Category',
    'products.noProducts': 'No products found',
    'products.addProductPrompt': 'Please add new products',
    'products.loading': 'Loading products...',
    'products.sku': 'SKU',
    'products.nameTh': 'Thai Name',
    'products.nameEn': 'English Name',
    'products.descriptionTh': 'Thai Description',
    'products.descriptionEn': 'English Description',
    'products.basePrice': 'Sale Price',
    'products.costPrice': 'Cost Price',
    'products.stockQuantity': 'Stock Quantity',
    'products.minStockLevel': 'Min Stock Level',
    'products.unit': 'Unit',
    'products.image': 'Image',
    'products.uploadImage': 'Upload Image',
    'products.editProduct': 'Edit Product',
    'products.saveSuccess': 'Product saved successfully',
    'products.filterByCategory': 'Filter by Category',
    'products.filterByPrice': 'Filter by Price',
    'products.filterByStock': 'Filter by Stock',
    'products.allCategories': 'All Categories',
    'products.lowStock': 'Low Stock',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.priceRange': 'Price Range',
    'products.minPrice': 'Min Price',
    'products.maxPrice': 'Max Price',
    'products.clearFilters': 'Clear Filters',
    
    // Inventory
    'inventory.title': 'Inventory',
    'inventory.comingSoon': 'Coming Soon',
    
    // Reports
    'reports.title': 'Reports',
    'reports.comingSoon': 'Coming Soon',
    
    // AI Symptom Checker
    'ai.title': 'AI Symptom Checker',
    'ai.subtitle': 'AI-powered drug recommendation system',
    'ai.disclaimer': '⚠️ Disclaimer: This system provides preliminary information only and is not a medical diagnosis. If symptoms are severe or persist, please consult a doctor.',
    'ai.patientInfo': 'Patient Information',
    'ai.age': 'Age',
    'ai.ageYears': 'years',
    'ai.pregnant': 'Pregnant or Breastfeeding?',
    'ai.yes': 'Yes',
    'ai.no': 'No',
    'ai.allergies': 'Drug Allergies',
    'ai.allergiesPlaceholder': 'e.g., Penicillin, Aspirin',
    'ai.currentMeds': 'Current Medications',
    'ai.currentMedsPlaceholder': 'e.g., Blood pressure medication, Diabetes medication',
    'ai.chronicConditions': 'Chronic Conditions',
    'ai.chronicConditionsPlaceholder': 'e.g., Diabetes, Hypertension, Asthma',
    'ai.symptomDuration': 'Symptom Duration',
    'ai.lessThan1Day': 'Less than 1 day',
    'ai.1to3Days': '1-3 days',
    'ai.3to7Days': '3-7 days',
    'ai.moreThan1Week': 'More than 1 week',
    'ai.symptoms': 'Symptoms',
    'ai.symptomsPlaceholder': 'Describe symptoms in detail, e.g., headache, fever, sore throat, cough, runny nose',
    'ai.analyze': 'Analyze & Recommend',
    'ai.analyzing': 'Analyzing...',
    'ai.results': 'Analysis Results',
    'ai.recommendations': 'Recommended Medications',
    'ai.warnings': 'Warnings',
    'ai.dosage': 'Dosage',
    'ai.price': 'Price',
    'ai.stock': 'Stock',
    'ai.addToCart': 'Add to Cart',
    'ai.noResults': 'No suitable medication found. Please consult a pharmacist or doctor.',
    'ai.error': 'An error occurred. Please try again.',
    'ai.apiKeyMissing': 'Please set Google Gemini API Key in .env',
    'ai.seeDoctor': 'Recommend seeing a doctor',
    'ai.reset': 'Reset',
    
    // User Management
    'userManagement.title': 'User Management',
    'userManagement.subtitle': 'Manage user accounts and access permissions',
    'userManagement.addUser': 'Add User',
    'userManagement.editUser': 'Edit User',
    'userManagement.username': 'Username',
    'userManagement.email': 'Email',
    'userManagement.fullName': 'Full Name',
    'userManagement.role': 'Role',
    'userManagement.password': 'Password',
    'userManagement.active': 'Active',
    'userManagement.search': 'Search users...',
    'userManagement.noUsers': 'No users found',
    'userManagement.addUserPrompt': 'Click "Add User" to create a new account',
    'userManagement.cancel': 'Cancel',
    'userManagement.save': 'Save',
    'userManagement.create': 'Create',
    'userManagement.emailAuto': 'Email (leave blank = auto-generate)',
    'userManagement.passwordHint': 'Password (leave blank = 888888)',
    'userManagement.activeAccount': 'Activate this account',
    
    // Roles
    'role.owner': 'Owner',
    'role.manager': 'Manager',
    'role.pharmacist': 'Pharmacist',
    'role.partTime': 'Part-time',
    'role.accountant': 'Accountant',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'System settings and integrations',
    'settings.userManagement': 'User Management',
    'settings.helpManual': 'Help Manual',
    // Settings - Business
    'settings.section.business': 'Business Settings',
    'settings.section.externalConnections': 'External Connections',
    'settings.section.audit': 'Audit - Monitoring & Control',
    'settings.dashboard': 'Dashboard',
    'settings.dashboardDesc': 'Sales overview and statistics',
    'settings.salesChannels': 'Sales Channels',
    'settings.salesChannelsDesc': 'Configured',
    'settings.salesChannelsUnit': 'channels',
    'settings.paymentChannels': 'Payment Channels',
    'settings.paymentChannelsDesc': 'Set up payment methods',
    'settings.paymentChannelsStatus': 'Active',
    'settings.shopInfo': 'Shop Information',
    'settings.userManagementTitle': 'User Management',
    'settings.userManagementDesc': 'System users',
    'settings.usersCount': 'users',
    'settings.employeeManagement': 'Employee Management',
    'settings.employeeManagementDesc': 'Set up employees and permissions',
    'settings.warehouse': 'Warehouse',
    'settings.warehouseDesc': 'Manage warehouse and stock',
    'settings.productCategories': 'Product Categories',
    'settings.productCategoriesDesc': 'Manage categories and subcategories',
    'settings.expenseCategories': 'Expense Categories',
    'settings.expenseCategoriesDesc': 'Set up account codes and chart of accounts',
    'settings.paymentRules': 'Payment Rules',
    'settings.paymentRulesDesc': 'Set up payment methods by keyword',
    // Settings - External Connections
    'settings.flowAccount': 'FlowAccount Integration',
    'settings.flowAccountDesc': 'Accounting and tax invoices',
    'settings.flowAccountConnected': 'Connected',
    'settings.flowAccountDisconnected': 'Not connected',
    'settings.zortOut': 'ZortOut Integration',
    'settings.zortOutDesc': 'Stock management system',
    'settings.zortOutStatus': 'Ready',
    // Settings - Audit
    'settings.executiveSummary': 'Business Overview',
    'settings.executiveSummaryDesc': 'Executive Summary for management',
    'settings.cashierClosing': 'Store Closing / Cash Count Report',
    'settings.cashierClosingDesc': 'Review closing history and cash drawer totals',
    'settings.negativeStock': 'Negative Stock Report',
    'settings.negativeStockDesc': 'Check products with negative stock and movements',
    'settings.stockAdjustment': 'Stock Adjustment Report',
    'settings.stockAdjustmentDesc': 'Review stock adjustments by users',
    'settings.stockTransfer': 'Inter-Warehouse Transfer Report',
    'settings.stockTransferDesc': 'Review product movements between warehouses',
    'settings.abnormalOrders': 'Abnormal Orders Report',
    'settings.abnormalOrdersDesc': 'Review price edits and free items',
    'settings.receiptTaxInvoice': 'Receipt/Tax Invoice Report',
    'settings.receiptTaxInvoiceDesc': 'Review receipt and tax invoice requests',
    'settings.nearExpiry': 'Near Expiry Products',
    'settings.nearExpiryDesc': 'Check products near expiry date',
    'settings.helpManagement': 'Help Manual Management',
    'settings.helpManagementDesc': 'Create and edit manuals for each page',
    
    // Page Titles (for pages linked from sidebar)
    'page.pos.title': 'Point of Sale',
    'page.pos.subtitle': 'In-store sales system',
    'page.salesOrders.title': 'Sales Orders',
    'page.products.title': 'Products',
    'page.products.subtitle': 'Manage all products',
    'page.platformManagement.title': 'Platform Management',
    'page.platformManagement.subtitle': 'Manage products across platforms',
    'page.crossChannelStock.title': 'Cross-Channel Stock',
    'page.crossChannelStock.subtitle': 'Cross-channel stock cut report',
    'page.contacts.title': 'Contacts',
    'page.contacts.subtitle': 'Manage customers and suppliers',
    'page.expenses.title': 'Documents',
    'page.expenses.subtitle': 'Manage all documents',
    'page.billScan.title': 'Bill Scan OCR',
    'page.billScan.subtitle': 'Scan and record bills automatically',
    'page.taxInvoices.title': 'Sales Tax Invoices',
    'page.taxInvoices.subtitle': 'Manage tax invoices',
    'page.workSchedule.title': 'Work Schedule',
    'page.workSchedule.subtitle': 'Manage work schedule',
    'page.dashboard.subtitle': 'Sales overview and statistics',
    'page.warehouse.title': 'Warehouse',
    'page.warehouse.subtitle': 'Manage warehouse and stock',
    'page.categories.title': 'Product Categories',
    'page.categories.subtitle': 'Manage categories and subcategories',
    'page.paymentMethods.title': 'Payment Channels',
    'page.paymentMethods.subtitle': 'Set up payment methods',

    // Common
    'common.loading': 'Loading...',
    'common.inactive': 'Inactive',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.add': 'Add',
    'common.baht': '฿',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuthStore()
  const [language, setLanguageState] = useState<Language>('th')

  useEffect(() => {
    if (user?.language) {
      setLanguageState(user.language as Language)
    }
  }, [user])

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang)
    
    if (user?.id) {
      try {
        await supabase
          .from('users')
          .update({ language: lang })
          .eq('id', user.id)
        
        // Update local user state
        useAuthStore.getState().setUser({ ...user, language: lang })
      } catch (error) {
        console.error('Failed to save language preference:', error)
      }
    }
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
